---
deployment:
  tasks:

    # Copy latest repo files to live app
    - /bin/cp -R botchat-app/. /home/megasfuh/botchat_app/

    # Install dependencies + build
    - export PATH=/opt/cpanel/ea-nodejs20/bin:$PATH && cd /home/megasfuh/botchat_app && npm install && npm run build

    # Restart Node.js app
    - mkdir -p /home/megasfuh/botchat_app/tmp
    - touch /home/megasfuh/botchat_app/tmp/restart.txt